### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by imaginetheheadline** [May-Manmai/tic-tac-toe#1]
# Project 1

Nice work on this one May! I don't have a lot of comments. It looks like you've got a pretty good understanding of everything. Let me know if you have some questions. :)

## HTML

Very straight-forward, I like it

## CSS

CSS looks good, May.

### box-sizing

Remember to add `box-sizing: border-box;` to:

```css
* {
    font-family: Arial, Helvetica, sans-serif;
    text-align: center;
    background-color: rgba(222, 222, 222, 0.726);
}
```

This way all your elements will have predictable width and height.

### Borders

```css
#box0,
#box1,
#box2 {
    border-top: none;
}

#box0,
#box3,
#box6 {
    border-left: none;
}

#box6,
#box7,
#box8 {
    border-bottom: none;
}

#box2,
#box5,
#box8 {
    border-right: none;
}
```

Nice!

## JavaScript

JS also looks good. Nice and efficient.

Love this:

```js
allBoxes[0].textContent = '👊🤪';
allBoxes[1].textContent = '👊🤪';
allBoxes[2].textContent = '👊🤪';
```

### Functions

Nice use of functions.

### Code order

I would suggest to move some of your code around so that the main code that runs when the page loads is all together at the top. Right now you have functions mixed in with the running code. Also at the very bottom, you have some running code as well:

```js
restart.addEventListener('click', function () {
    window.location.reload();
    return false;
});
```

I would put all this at the top and keep the functions at the bottom. Or you could also make a `setup` function that sets up everything for the game like all these event listeners. Doing this will make your code easier to follow :)
